exp_name: hrl_shared_ppo
from_checkpoint: null
seed: 42
num_gpus: 1
num_workers: 10
num_envs_per_worker: 1
num_eval_workers: 4
eval_interval: 50
eval_episodes: 20

stop_timesteps: 200000000

# env configs
env: football
scenario: academy_3_vs_1_with_keeper
num_agents: 3
training_shaping_rewards: checkpoints,shooting
context_size: 5
context_type: continuous
high_level_interval: 10

# algorithm configs
high_level_config:
  gamma: 0.99
  gae_lambda: 1.0
  kl_coeff: 0.2
  rollout_fragment_length: 1000
  train_batch_size: 10000
  sgd_minibatch_size: 1000
  num_sgd_iter: 30
  lr: 0.0001
  entropy_coeff: 0.0
  clip_param: 0.3
  vf_clip_param: 10.0

low_level_config:
  gamma: 0.99
  gae_lambda: 1.0
  kl_coeff: 0.2
  rollout_fragment_length: 1000
  train_batch_size: 10000
  sgd_minibatch_size: 1000
  num_sgd_iter: 30
  lr: 0.0001
  entropy_coeff: 0.0
  clip_param: 0.3
  vf_clip_param: 10.0