exp_name: att_com_curriculum_hrl
from_checkpoint: null
seed: 42
num_gpus: 1
num_workers: 120
num_envs_per_worker: 5
num_eval_workers: 2
eval_interval: 5
eval_episodes: 20

stop_timesteps: 200000000

# target env configs
env: football
scenario: 11_vs_11_easy_stochastic
num_agents: 10
training_shaping_rewards: checkpoints,shooting
context_size: 3
context_type: discrete
high_level_interval: 10

# algorithm configs
high_level_config:
  gamma: 0.99
  gae_lambda: 1.0
  kl_coeff: 0.2
  rollout_fragment_length: 100
  train_batch_size: 30000
  sgd_minibatch_size: 2000
  num_sgd_iter: 60
  lr: 0.0001
  entropy_coeff: 0.0
  clip_param: 0.3
  vf_clip_param: 10.0
  model_config:
    encoder_hidden_layers: [256, 256]
    num_heads: 8
    head_dim: 64
    decoder_hidden_layers: [256]

low_level_config:
  gamma: 0.99
  gae_lambda: 1.0
  kl_coeff: 0.2
  rollout_fragment_length: 1000
  train_batch_size: 100000
  sgd_minibatch_size: 10000
  num_sgd_iter: 30
  lr: 0.0001
  entropy_coeff: 0.0
  clip_param: 0.3
  vf_clip_param: 10.0

# curriculum configs
teacher: contextual_bandit
teacher_config:
  num_contexts: 3
  gamma: 0.3
  update_interval: 20