exp_name: att_com
from_checkpoint: null
seed: 42
num_gpus: 1
num_workers: 10
num_envs_per_worker: 3
num_eval_workers: 4
eval_interval: 50
eval_episodes: 20

stop_timesteps: 100000000

# env configs
env: football
scenario: academy_3_vs_1_with_keeper
num_agents: 3
training_shaping_rewards: null

# algorithm configs
gamma: 0.99
gae_lambda: 1.0
kl_coeff: 0.2
rollout_fragment_length: 100
train_batch_size: 10000
sgd_minibatch_size: 1000
num_sgd_iter: 30
lr: 0.0001
entropy_coeff: 0.0
clip_param: 0.3
vf_clip_param: 10.0
model_config:
  encoder_hidden_layers: [256, 256]
  num_heads: 8
  head_dim: 64
  decoder_hidden_layers: [256]
