exp_name: shared_ppo
from_checkpoint: null
seed: 123
num_gpus: 1
num_workers: 13
num_envs_per_worker: 5
num_eval_workers: 1
eval_interval: 20
eval_episodes: 5

stop_timesteps: 60000000

# env configs
env: mpe
scenario: curriculum_simple_spread_po
env_config:
  num_agent_candidates: [2, 4, 8, 16, 32]
  num_observable_agents: 1
  episode_length: 70

# algorithm configs
gamma: 0.99
gae_lambda: 1.0
kl_coeff: 0.5
rollout_fragment_length: 100
train_batch_size: 5000
sgd_minibatch_size: 500
num_sgd_iter: 10
lr: 0.0001
entropy_coeff: 0.0
clip_param: 0.3
vf_clip_param: 10.0

# curriculum configs
teacher: mpe_contextual_bandit
teacher_config:
  num_contexts: 3
  gamma: 0.3
  update_interval: 20