exp_name: att_com
from_checkpoint: null
seed: 42
num_gpus: 1
num_workers: 1
num_envs_per_worker: 1
num_eval_workers: 1
eval_interval: 20
eval_episodes: 5

stop_timesteps: 60000000

# env configs
env: mpe
scenario: curriculum_push_ball_po
env_config:
  num_agents: 16
  num_observable_agents: 1
  episode_length: 25

# algorithm configs
gamma: 0.99
gae_lambda: 1.0
kl_coeff: 0.5
num_sgd_iter: 10
lr: 0.0001
entropy_coeff: 0.0
clip_param: 0.3
vf_clip_param: 10.0
model_config:
  encoder_hidden_layers: [128, 128]
  num_heads: 8
  head_dim: 64
  decoder_hidden_layers: [128]
